name: GitHub_CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest]
        php-versions: ['7.2', '7.3', '7.4', '8.0', '8.1']
    runs-on: ${{ matrix.operating-system }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP (LINUX)
        if: runner.os == 'Linux'
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, intl, pcov
          ini-values: post_max_size=256M, log_errors=1
          tools: pecl

      - name: Setup PHP (WIN)
        if: runner.os == 'Windows'
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, intl, pcov
          ini-values: post_max_size=256M, log_errors=1
          tools: pecl
          coverage: pcov

      - name: Check PHP Version
        run: php -v

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Remove lock file for linux
        if: runner.os == 'Linux'
        run: rm -rf composer.lock

      - name: Remove lock file for windows
        if: runner.os == 'Windows'
        run: del composer.lock

      - name: Install dependencies
        run: composer clearcache && composer install --prefer-dist --no-suggest

      - name: Run Tests (Linux)
        if: runner.os == 'Linux'
        run: composer all

      - name: Run Tests (Windows)
        if: runner.os == 'Windows'
        run: vendor\bin\phpunit && composer analyse

      - name: Codecov
        if: runner.os == 'Linux'
        run: bash <(curl -s https://codecov.io/bash) -t ${{ secrets.VITE_CODECOV }}
