name: GitHub_CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest]
        php-versions: ['7.1', '7.2', '7.3', '7.4', '8.0', '8.1']
    runs-on: ${{ matrix.operating-system }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, intl, pcov
          ini-values: post_max_size=256M, log_errors=1
          tools: pecl

      - name: Check PHP Version
        run: php -v

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name:  Install
        run:   |
         if [ matrix.operating-system == 'ubuntu-latest' ]; then
              rm -rf composer.lock
         elif [ matrix.operating-system == 'windows-latest' ]; then
              del composer.lock
         else
              echo "$RUNNER_OS not supported"
              exit 1
         fi
        shell: bash

      - name: Install dependencies
        run: composer clearcache && composer install --prefer-dist --no-suggest

      - name: Run Tests
        run: composer all

      - name: Codecov
        run: bash <(curl -s https://codecov.io/bash) -t ${{ secrets.VITE_CODECOV }}
